spring:
  application:
    name: WEB-SERVICE
server:
  port: 8083

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  servlet:
    session:
      timeout: 15m   # auto logout after 15 minutes inactivity

jwt:
  secret: ${JWT_SECRET:supersecretkeysupersecretkeysadasdkasdkashdkashdaskdhaskdhaskjd}

internal:
  secret: ${INTERNAL_SECRET:gateway-secret-123456789101112131415}