server:
  port: 8084

spring:
  application:
    name: EXAM-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/exam_db
    username: root
    password: Mockingbird@1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

internal:
  secret: gateway-secret-123456789101112131415